#!/usr/bin/env python3
"""Validate Brick Puzzle level/replay fixtures and produce catalog reports."""

from __future__ import annotations

import argparse
from collections import Counter
from dataclasses import asdict, dataclass
import json
from pathlib import Path
import re
import sys
from typing import Any


REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_LEVELS_DIRECTORY = REPOSITORY_ROOT / "BrickPuzzle/Resources/Levels"
DEFAULT_REPLAYS_DIRECTORY = REPOSITORY_ROOT / "BrickPuzzle/Resources/Replays"
LEVEL_ID_PATTERN = re.compile(r"^prototype-(\d{3})$")
DIFFICULTIES = ("tutorial", "easy", "medium", "hard")
VALIDATION_STATUSES = ("draft", "replayValidated")


@dataclass(frozen=True)
class LevelRecord:
    level_id: str
    title: str
    difficulty: str
    mechanics: tuple[str, ...]
    brick_count: int
    minimum_known_shot_count: int
    three_star_shot_limit: int


@dataclass(frozen=True)
class CatalogSummary:
    levels: tuple[LevelRecord, ...]

    @property
    def difficulty_counts(self) -> dict[str, int]:
        counts = Counter(level.difficulty for level in self.levels)
        return {difficulty: counts[difficulty] for difficulty in DIFFICULTIES}

    @property
    def mechanic_counts(self) -> dict[str, int]:
        counts = Counter(mechanic for level in self.levels for mechanic in level.mechanics)
        return dict(sorted(counts.items()))

    def as_json(self) -> str:
        payload = {
            "levelCount": len(self.levels),
            "difficultyCounts": self.difficulty_counts,
            "mechanicCounts": self.mechanic_counts,
            "levels": [asdict(level) for level in self.levels],
        }
        return json.dumps(payload, indent=2, sort_keys=True) + "\n"

    def as_markdown(self) -> str:
        lines = [
            "# Level Catalog Report",
            "",
            "Generated by `.github/scripts/level_catalog.py`. Do not edit by hand.",
            "",
            "## Summary",
            "",
            f"- Levels: {len(self.levels)}",
            "- Matching clean replays: one per level",
            "- Catalog ids: unique, contiguous, and filename-aligned",
            "",
            "## Difficulty Distribution",
            "",
            "| Difficulty | Count |",
            "| --- | ---: |",
        ]
        lines.extend(
            f"| {difficulty.title()} | {count} |"
            for difficulty, count in self.difficulty_counts.items()
        )
        lines.extend([
            "",
            "## Mechanic Coverage",
            "",
            "| Mechanic | Levels |",
            "| --- | ---: |",
        ])
        lines.extend(
            f"| `{mechanic}` | {count} |"
            for mechanic, count in self.mechanic_counts.items()
        )
        lines.extend([
            "",
            "## Catalog",
            "",
            "| Level | Title | Difficulty | Bricks | Known shots | Three-star limit | Mechanics |",
            "| --- | --- | --- | ---: | ---: | ---: | --- |",
        ])
        for level in self.levels:
            mechanics = ", ".join(f"`{mechanic}`" for mechanic in level.mechanics)
            lines.append(
                f"| `{level.level_id}` | {level.title} | {level.difficulty.title()} | "
                f"{level.brick_count} | {level.minimum_known_shot_count} | "
                f"{level.three_star_shot_limit} | {mechanics} |"
            )
        return "\n".join(lines) + "\n"


class CatalogValidationError(Exception):
    def __init__(self, errors: list[str]) -> None:
        self.errors = tuple(sorted(errors))
        super().__init__("Level catalog validation failed:\n- " + "\n- ".join(self.errors))


def load_json(path: Path, errors: list[str]) -> dict[str, Any] | None:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        errors.append(f"{path.name}: cannot decode JSON: {error}")
        return None
    if not isinstance(payload, dict):
        errors.append(f"{path.name}: top-level JSON value must be an object")
        return None
    return payload


def positive_integer(value: Any) -> bool:
    return isinstance(value, int) and not isinstance(value, bool) and value > 0


def validate_level(path: Path, level: dict[str, Any], errors: list[str]) -> LevelRecord | None:
    level_id = level.get("id")
    if not isinstance(level_id, str) or LEVEL_ID_PATTERN.fullmatch(level_id) is None:
        errors.append(f"{path.name}: id must match prototype-NNN")
        return None
    if path.stem != level_id:
        errors.append(f"{path.name}: filename must match level id {level_id}")

    title = level.get("title")
    if not isinstance(title, str) or not title.strip():
        errors.append(f"{path.name}: title must be a non-empty string")
        title = ""

    columns = level.get("columns")
    rows = level.get("rows")
    if not positive_integer(columns) or not positive_integer(rows):
        errors.append(f"{path.name}: columns and rows must be positive integers")

    bricks = level.get("bricks")
    if not isinstance(bricks, list) or not bricks:
        errors.append(f"{path.name}: bricks must be a non-empty array")
        bricks = []
    brick_ids: set[str] = set()
    coordinates: set[tuple[int, int]] = set()
    for index, brick in enumerate(bricks):
        prefix = f"{path.name}: brick[{index}]"
        if not isinstance(brick, dict):
            errors.append(f"{prefix} must be an object")
            continue
        brick_id = brick.get("id")
        if not isinstance(brick_id, str) or not brick_id:
            errors.append(f"{prefix} id must be a non-empty string")
        elif brick_id in brick_ids:
            errors.append(f"{path.name}: duplicate brick id {brick_id}")
        else:
            brick_ids.add(brick_id)
        row = brick.get("row")
        column = brick.get("column")
        if not isinstance(row, int) or not isinstance(column, int):
            errors.append(f"{prefix} row and column must be integers")
        else:
            coordinate = (row, column)
            if coordinate in coordinates:
                errors.append(f"{path.name}: duplicate brick coordinate {coordinate}")
            coordinates.add(coordinate)
            if positive_integer(rows) and not 0 <= row < rows:
                errors.append(f"{prefix} row {row} is outside 0..{rows - 1}")
            if positive_integer(columns) and not 0 <= column < columns:
                errors.append(f"{prefix} column {column} is outside 0..{columns - 1}")
        if not positive_integer(brick.get("hitPoints")):
            errors.append(f"{prefix} hitPoints must be a positive integer")

    available_powerups = level.get("availablePowerups")
    max_loadout = level.get("maxPowerupLoadoutSize")
    if not isinstance(available_powerups, list) or any(
        not isinstance(powerup, str) for powerup in available_powerups
    ):
        errors.append(f"{path.name}: availablePowerups must be an array of strings")
        available_powerups = []
    elif len(available_powerups) != len(set(available_powerups)):
        errors.append(f"{path.name}: availablePowerups must not contain duplicates")
    if not isinstance(max_loadout, int) or isinstance(max_loadout, bool) or max_loadout < 0:
        errors.append(f"{path.name}: maxPowerupLoadoutSize must be a non-negative integer")
    elif max_loadout > len(available_powerups):
        errors.append(f"{path.name}: maxPowerupLoadoutSize exceeds availablePowerups")

    star_rules = level.get("starRules")
    if not isinstance(star_rules, dict):
        errors.append(f"{path.name}: starRules must be an object")
        star_rules = {}
    two_star_limit = star_rules.get("twoStarShotLimit")
    three_star_limit = star_rules.get("threeStarShotLimit")
    if not positive_integer(two_star_limit) or not positive_integer(three_star_limit):
        errors.append(f"{path.name}: star shot limits must be positive integers")
        three_star_limit = 0
    elif two_star_limit < three_star_limit:
        errors.append(f"{path.name}: two-star limit cannot be lower than three-star limit")
    if not isinstance(star_rules.get("threeStarRequiresNoPowerups"), bool):
        errors.append(f"{path.name}: threeStarRequiresNoPowerups must be a boolean")

    metadata = level.get("metadata")
    if not isinstance(metadata, dict):
        errors.append(f"{path.name}: metadata must be an object")
        metadata = {}
    intended_solution = metadata.get("intendedSolution")
    if not isinstance(intended_solution, str) or not intended_solution.strip():
        errors.append(f"{path.name}: intendedSolution must be a non-empty string")
    minimum_shots = metadata.get("minimumKnownShotCount")
    if not positive_integer(minimum_shots):
        errors.append(f"{path.name}: minimumKnownShotCount must be a positive integer")
        minimum_shots = 0
    elif positive_integer(three_star_limit) and minimum_shots > three_star_limit:
        errors.append(f"{path.name}: minimumKnownShotCount exceeds three-star limit")
    mechanics = metadata.get("requiredMechanics")
    if not isinstance(mechanics, list) or not mechanics or any(
        not isinstance(mechanic, str) or not mechanic for mechanic in mechanics
    ):
        errors.append(f"{path.name}: requiredMechanics must be a non-empty array of strings")
        mechanics = []
    elif len(mechanics) != len(set(mechanics)):
        errors.append(f"{path.name}: requiredMechanics must not contain duplicates")
    difficulty = metadata.get("difficulty")
    if difficulty not in DIFFICULTIES:
        errors.append(f"{path.name}: difficulty must be one of {', '.join(DIFFICULTIES)}")
        difficulty = ""
    if metadata.get("validationStatus") not in VALIDATION_STATUSES:
        errors.append(f"{path.name}: validationStatus must be draft or replayValidated")

    referenced_ids: list[str] = []
    objective = level.get("objective", {})
    if isinstance(objective, dict):
        ordered_ids = objective.get("orderedBrickIDs", [])
        if isinstance(ordered_ids, list):
            referenced_ids.extend(identifier for identifier in ordered_ids if isinstance(identifier, str))
    for link_name, source_key, targets_key in (
        ("shieldLinks", "shieldID", "protectedBrickIDs"),
        ("keyLinks", "keyID", "lockedBrickIDs"),
    ):
        links = level.get(link_name, [])
        if not isinstance(links, list):
            errors.append(f"{path.name}: {link_name} must be an array")
            continue
        for link in links:
            if not isinstance(link, dict):
                errors.append(f"{path.name}: {link_name} entries must be objects")
                continue
            source_id = link.get(source_key)
            targets = link.get(targets_key)
            if isinstance(source_id, str):
                referenced_ids.append(source_id)
            if isinstance(targets, list):
                referenced_ids.extend(identifier for identifier in targets if isinstance(identifier, str))
    unknown_references = sorted(set(referenced_ids) - brick_ids)
    if unknown_references:
        errors.append(f"{path.name}: references unknown brick ids {', '.join(unknown_references)}")

    return LevelRecord(
        level_id=level_id,
        title=title,
        difficulty=difficulty,
        mechanics=tuple(mechanics),
        brick_count=len(bricks),
        minimum_known_shot_count=minimum_shots,
        three_star_shot_limit=three_star_limit,
    )


def validate_replay(
    path: Path,
    replay: dict[str, Any],
    level: dict[str, Any] | None,
    record: LevelRecord | None,
    errors: list[str],
) -> None:
    level_id = replay.get("levelID")
    if not isinstance(level_id, str):
        errors.append(f"{path.name}: levelID must be a string")
        return
    if path.name != f"{level_id}-clean.json":
        errors.append(f"{path.name}: clean replay filename must match levelID {level_id}")
    if level is None:
        errors.append(f"{path.name}: replay has no matching level {level_id}")
        return

    expected_outcome = replay.get("expectedOutcome")
    if not isinstance(expected_outcome, dict) or expected_outcome.get("completed") is not True:
        errors.append(f"{path.name}: clean replay must expect completion")
    if not isinstance(expected_outcome, dict) or expected_outcome.get("stars") != 3:
        errors.append(f"{path.name}: clean replay must expect three stars")

    shots = replay.get("shots")
    if not isinstance(shots, list) or not shots:
        errors.append(f"{path.name}: shots must be a non-empty array")
        shots = []
    if record is not None and len(shots) != record.minimum_known_shot_count:
        errors.append(
            f"{path.name}: shot count {len(shots)} does not match minimumKnownShotCount "
            f"{record.minimum_known_shot_count}"
        )

    star_rules = level.get("starRules", {})
    requires_clean = isinstance(star_rules, dict) and star_rules.get("threeStarRequiresNoPowerups") is True
    selected_powerups = replay.get("selectedPowerups")
    level_powerups = level.get("availablePowerups", [])
    available_powerups = (
        {powerup for powerup in level_powerups if isinstance(powerup, str)}
        if isinstance(level_powerups, list)
        else set()
    )
    selected_powerup_set: set[str] = set()
    if not isinstance(selected_powerups, list) or any(
        not isinstance(powerup, str) for powerup in selected_powerups
    ):
        errors.append(f"{path.name}: selectedPowerups must be an array of strings")
    else:
        selected_powerup_set = set(selected_powerups)
        unknown_powerups = sorted(selected_powerup_set - available_powerups)
        if unknown_powerups:
            errors.append(
                f"{path.name}: selects unavailable powerups {', '.join(unknown_powerups)}"
            )
        if len(selected_powerups) != len(selected_powerup_set):
            errors.append(f"{path.name}: selectedPowerups must not contain duplicates")
        max_loadout = level.get("maxPowerupLoadoutSize")
        if isinstance(max_loadout, int) and len(selected_powerups) > max_loadout:
            errors.append(f"{path.name}: selectedPowerups exceeds maxPowerupLoadoutSize")
        if requires_clean and selected_powerups:
            errors.append(f"{path.name}: clean three-star replay must not select powerups")

    brick_ids = {
        brick.get("id")
        for brick in level.get("bricks", [])
        if isinstance(brick, dict) and isinstance(brick.get("id"), str)
    }
    for index, shot in enumerate(shots):
        if not isinstance(shot, dict):
            errors.append(f"{path.name}: shot[{index}] must be an object")
            continue
        angle = shot.get("aimAngleDegrees")
        if not isinstance(angle, (int, float)) or isinstance(angle, bool) or not 10 <= angle <= 170:
            errors.append(f"{path.name}: shot[{index}] aimAngleDegrees must be between 10 and 170")
        used_powerups = shot.get("usedPowerups")
        if not isinstance(used_powerups, list) or any(
            not isinstance(powerup, str) for powerup in used_powerups
        ):
            errors.append(f"{path.name}: shot[{index}] usedPowerups must be an array of strings")
        else:
            unknown_powerups = sorted(set(used_powerups) - available_powerups)
            if unknown_powerups:
                errors.append(
                    f"{path.name}: shot[{index}] uses unavailable powerups "
                    f"{', '.join(unknown_powerups)}"
                )
            unselected_powerups = sorted(set(used_powerups) - selected_powerup_set)
            if unselected_powerups:
                errors.append(
                    f"{path.name}: shot[{index}] uses unselected powerups "
                    f"{', '.join(unselected_powerups)}"
                )
            if requires_clean and used_powerups:
                errors.append(f"{path.name}: clean three-star replay must not use powerups")
        destroyed_ids = shot.get("destroyedBrickIDs")
        if not isinstance(destroyed_ids, list) or any(
            not isinstance(identifier, str) for identifier in destroyed_ids
        ):
            errors.append(f"{path.name}: shot[{index}] destroyedBrickIDs must be an array of strings")
        else:
            unknown_ids = sorted(set(destroyed_ids) - brick_ids)
            if unknown_ids:
                errors.append(f"{path.name}: shot[{index}] destroys unknown ids {', '.join(unknown_ids)}")


def validate_catalog(levels_directory: Path, replays_directory: Path) -> CatalogSummary:
    errors: list[str] = []
    if not levels_directory.is_dir():
        raise CatalogValidationError([f"missing levels directory: {levels_directory}"])
    if not replays_directory.is_dir():
        raise CatalogValidationError([f"missing replays directory: {replays_directory}"])

    level_documents: dict[str, dict[str, Any]] = {}
    records: dict[str, LevelRecord] = {}
    for path in sorted(levels_directory.glob("*.json")):
        level = load_json(path, errors)
        if level is None:
            continue
        level_id = level.get("id")
        if isinstance(level_id, str):
            if level_id in level_documents:
                errors.append(f"{path.name}: duplicate level id {level_id}")
            else:
                level_documents[level_id] = level
        record = validate_level(path, level, errors)
        if record is not None and record.level_id not in records:
            records[record.level_id] = record

    numeric_ids = sorted(
        int(match.group(1))
        for level_id in level_documents
        if (match := LEVEL_ID_PATTERN.fullmatch(level_id)) is not None
    )
    if numeric_ids and numeric_ids != list(range(1, numeric_ids[-1] + 1)):
        errors.append("level ids must form a contiguous sequence beginning at prototype-001")

    replay_level_ids: set[str] = set()
    for path in sorted(replays_directory.glob("*.json")):
        replay = load_json(path, errors)
        if replay is None:
            continue
        level_id = replay.get("levelID")
        if isinstance(level_id, str):
            if level_id in replay_level_ids:
                errors.append(f"{path.name}: duplicate replay for {level_id}")
            replay_level_ids.add(level_id)
        validate_replay(path, replay, level_documents.get(level_id), records.get(level_id), errors)

    missing_replays = sorted(set(level_documents) - replay_level_ids)
    if missing_replays:
        errors.append(f"missing clean replays for {', '.join(missing_replays)}")
    orphan_replays = sorted(replay_level_ids - set(level_documents))
    if orphan_replays:
        errors.append(f"orphan clean replays for {', '.join(orphan_replays)}")
    if not level_documents:
        errors.append("catalog must contain at least one level")

    if errors:
        raise CatalogValidationError(errors)
    return CatalogSummary(levels=tuple(records[level_id] for level_id in sorted(records)))


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--levels", type=Path, default=DEFAULT_LEVELS_DIRECTORY)
    parser.add_argument("--replays", type=Path, default=DEFAULT_REPLAYS_DIRECTORY)
    subparsers = parser.add_subparsers(dest="command", required=True)
    subparsers.add_parser("validate")
    report_parser = subparsers.add_parser("report")
    report_parser.add_argument("--format", choices=("markdown", "json"), default="markdown")
    output_group = report_parser.add_mutually_exclusive_group()
    output_group.add_argument("--output", type=Path)
    output_group.add_argument("--check", type=Path)
    return parser.parse_args()


def main() -> int:
    arguments = parse_arguments()
    try:
        summary = validate_catalog(arguments.levels, arguments.replays)
    except CatalogValidationError as error:
        print(error, file=sys.stderr)
        return 1

    if arguments.command == "validate":
        print(f"Validated {len(summary.levels)} levels and matching clean replays.")
        return 0

    report = summary.as_markdown() if arguments.format == "markdown" else summary.as_json()
    if arguments.check:
        try:
            existing_report = arguments.check.read_text(encoding="utf-8")
        except OSError as error:
            print(f"Cannot read report for comparison: {error}", file=sys.stderr)
            return 1
        if existing_report != report:
            print(f"Catalog report is stale: {arguments.check}", file=sys.stderr)
            return 1
        print(f"Catalog report is current: {arguments.check}")
    elif arguments.output:
        arguments.output.parent.mkdir(parents=True, exist_ok=True)
        arguments.output.write_text(report, encoding="utf-8")
        print(f"Wrote catalog report: {arguments.output}")
    else:
        print(report, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
